### ISSUE TITLE
Crash happen when try to select last empty line in a paragraph

### ISSUE THREAD

**Issue by AhmedSalahYouis** [MohamedRejeb/Compose-Rich-Editor#127]
Hi Mohamed,
I face a crash when I try to select last empty line in a paragraph

java.lang.IllegalArgumentException: lineIndex(258) is out of bounds [0, 11)
                                                                                                    	at androidx.compose.ui.text.MultiParagraph.requireLineIndexInRange(MultiParagraph.kt:785)
                                                                                                    	at androidx.compose.ui.text.MultiParagraph.getLineLeft(MultiParagraph.kt:661)
                                                                                                    	at androidx.compose.ui.text.TextLayoutResult.getLineLeft(TextLayoutResult.kt:439)
                                                                                                    	at androidx.compose.foundation.text.TextLayoutResultProxy.isPositionOnText-k-4lQ0M(TextLayoutResultProxy.kt:65)
                                                                                                    	at androidx.compose.foundation.text.selection.TextFieldSelectionManager$touchSelectionObserver$1.onStart-k-4lQ0M(TextFieldSelectionManager.kt:181)
                                                                                                    	at androidx.compose.foundation.text.LongPressTextDragObserverKt$detectDragGesturesAfterLongPressWithObserver$2.invoke-k-4lQ0M(LongPressTextDragObserver.kt:69)
                                                                                                    	at androidx.compose.foundation.text.LongPressTextDragObserverKt$detectDragGesturesAfterLongPressWithObserver$2.invoke(LongPressTextDragObserver.kt:63)
                                                                                                    	at androidx.compose.foundation.gestures.DragGestureDetectorKt$detectDragGesturesAfterLongPress$5.invokeSuspend(DragGestureDetector.kt:238)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine$withTimeout$job$1.invokeSuspend(SuspendingPointerInputFilter.kt:724)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:250)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7886)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@14a90f4, androidx.compose.runtime.BroadcastFrameClock@5a2401d, StandaloneCoroutine{Cancelling}@90c5292, AndroidUiDispatcher@a53d463]

**Comment by MohamedRejeb** [comment]
Hi, 
Thanks for reporting this issue, I will check it

**Comment by mohamedhamdy-Cis** [comment]
Hi @MohamedRejeb
 Any update regarding this crash or how we can avoid it

**Comment by mohamedhamdy-Cis** [comment]
i already check issue and found that it send index of length of paragraph instead of last line index  like here
java.lang.IllegalArgumentException: lineIndex(258) is out of bounds [0, 11)
258 is the length of all paragraph and it work normally with out issue when add space in this empty line before long press 
we notice that you are making this extension  "TextLayoutResultEXT" if this may cause crash.

**Comment by MohamedRejeb** [comment]
I didn't manage to reproduce this problem. I'm publishing a new version 1.0.0-beta05, let me know if you still have this issue with the new version.
