### ISSUE TITLE
Doesn't work with latest jetbrains markdown parser

### ISSUE THREAD

**Issue by VladPetryshyn** [MohamedRejeb/Compose-Rich-Editor#146]
My jetbrains markdown version is: 0.5.0,
and when I try to use this project with it, It gives me this error:
```  E  FATAL EXCEPTION: main
                                                                                                    Process: com.vladpetryshyn.vyao, PID: 27756
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'org.intellij.markdown.parser.MarkerProcessor org.intellij.markdown.parser.MarkerProcessorFactory.createMarkerProcessor(org.intellij.markdown.parser.ProductionHolder)' on a null object reference
                                                                                                    	at org.intellij.markdown.parser.MarkdownParser.doParse(MarkdownParser.kt:50)
                                                                                                    	at org.intellij.markdown.parser.MarkdownParser.parse(MarkdownParser.kt:26)
                                                                                                    	at org.intellij.markdown.parser.MarkdownParser.buildMarkdownTreeFromString(MarkdownParser.kt:21)
                                                                                                    	at com.mohamedrejeb.richeditor.parser.markdown.MarkdownUtilsKt.encodeMarkdownToRichText(MarkdownUtils.kt:23)
                                                                                                    	at com.mohamedrejeb.richeditor.parser.markdown.RichTextStateMarkdownParser.encode(RichTextStateMarkdownParser.kt:29)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.setMarkdown(RichTextState.kt:2067)
                                                                                                    	at com.vladpetryshyn.vyao.ui.updateTask.UpdateTaskScreenKt$UpdateTaskScreen$1.invokeSuspend(UpdateTaskScreen.kt:91)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@124d476, androidx.compose.runtime.BroadcastFrameClock@eae9a77, StandaloneCoroutine{Cancelling}@27236e4, AndroidUiDispatcher@fb3074d]
2023-11-29 22:17:57.761 27756-27756 Process
```

I fixed it, by looking at the gradle dependencies inside of your project, by setting org.jetbrains:markdown version to version specified in your gradle file

**Comment by MohamedRejeb** [comment]
I'll publish a new release with a new version of JetBrains markdown. 
Thanks
