### ISSUE TITLE
RichText exception in LazyLists (maxLines)

### ISSUE THREAD

**Issue by Efimj** [MohamedRejeb/Compose-Rich-Editor#166]
I have a LazyVerticalStaggeredGrid component and when this element repeatedly wants to be rendered I get an exception.
I noticed that the exception only occurs with the parameter **`maxLines`**, if remove it, the exception will not appear.
I also noticed that this happens if there was **`Ordered list`** in the element.

Element:
```
@Composable
private fun NoteContent(text: String?, bodyStyle: TextStyle) {
    var headerLineCount by remember { mutableStateOf(1) }
    val richTextState = rememberRichTextState()

    LaunchedEffect(text) {
        if (text !== null && richTextState.annotatedString.text !== text)
            richTextState.setHtml(text)
        else
            richTextState.setText("")
    }
    RichText(
        state = richTextState,
        maxLines = 8 - headerLineCount,
        overflow = TextOverflow.Ellipsis,
        style = bodyStyle,
        color = CustomTheme.colors.textSecondary,
    )
}
```

Exception:
```
FATAL EXCEPTION: main
                                                                                                    Process: com.jobik.shkiper, PID: 6708
                                                                                                    java.lang.ArrayIndexOutOfBoundsException: length=5; index=-2
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:439)
                                                                                                    	at androidx.compose.ui.text.MultiParagraph.getHorizontalPosition(MultiParagraph.kt:566)
                                                                                                    	at androidx.compose.ui.text.TextLayoutResult.getHorizontalPosition(TextLayoutResult.kt:491)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.adjustRichParagraphLayout(RichTextState.kt:1816)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.onTextLayout$richeditor_compose_release(RichTextState.kt:1802)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextKt$BasicRichText$4.invoke(BasicRichText.kt:71)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextKt$BasicRichText$4.invoke(BasicRichText.kt:39)
                                                                                                    	at androidx.compose.foundation.text.modifiers.TextAnnotatedStringNode.measure-3p2s80s(TextAnnotatedStringNode.kt:278)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                                                                    	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1499)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1495)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at 
```androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1495)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:35)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:560)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:539)
                                                                                                    	at androidx.compose.foundation.layout.RowColumnMeasurementHelper.measureWithoutPlacing-_EkL_-Y(RowColumnMeasurementHelper.kt:112)
                                                                                                    	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s(RowColumnImpl.kt:71)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                                                                    	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Padding.kt:397)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1499)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1495)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1495)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:35)

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. You are giving a big help to make this library better.
