### ISSUE TITLE
RichText exception (IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by Efimj** [MohamedRejeb/Compose-Rich-Editor#173]
I noticed that sometimes an exception appears, I read the state that comes in **`RickText`**

```
<ul><li style="text-align: left;"></li></ul><p style="text-align: left;">d</p><ul><li style="text-align: left;">dw</li><li style="text-align: left;">d </li></ul><ol><li style="text-align: left;">d</li><li style="text-align: left;">f </li><li style="text-align: left;"><code-span>dwdd</code-span> </li><li style="text-align: left;"><span style="color: rgba(176, 121, 255, 1.0);">dwd<span style="background: rgba(176, 121, 255, 1.0);">dwd</span></span> </li></ol>
```

This is what the text looks like in **`RichTextEditor`**
![image](https://github.com/MohamedRejeb/Compose-Rich-Editor/assets/87390257/88178250-8838-47dd-a4f4-0f062c74e68e)

This HTML code when I go to **`RichText`** throws an exception:

```
FATAL EXCEPTION: main
Process: com.jobik.shkiper, PID: 18747
java.lang.IndexOutOfBoundsException: Index -8 out of bounds for length 7
 at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
 at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
 at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
 at java.util.Objects.checkIndex(Objects.java:359)
 at java.util.ArrayList.get(ArrayList.java:434)
 at androidx.compose.ui.text.MultiParagraph.getLineForOffset(MultiParagraph.kt:654)
 at androidx.compose.ui.text.TextLayoutResult.getLineForOffset(TextLayoutResult.kt:458)
 at com.mohamedrejeb.richeditor.utils.TextLayoutResultExtKt.getBoundingBoxes(TextLayoutResultExt.kt:24)
 at com.mohamedrejeb.richeditor.model.RichSpanStyle$Code.drawCustomStyle-zdrCDHg(RichSpanStyle.kt:82)
 at com.mohamedrejeb.richeditor.ui.ModifierExtKt$drawRichSpanStyle$1.invoke(ModifierExt.kt:42)
 at com.mohamedrejeb.richeditor.ui.ModifierExtKt$drawRichSpanStyle$1.invoke(ModifierExt.kt:16)
 at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:116)
 at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
 at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
 at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:365)
 at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
 at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
 at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
 at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
 at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
 at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
 at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
 at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
 at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
 at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
 at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
 at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
 at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
 at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
 at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
 at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
 at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
 at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
 at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
 at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
 at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
 at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:305)
 at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1138)
 at android.view.View.draw(View.java:23892)
 at android.view.View.updateDisplayListIfDirty(View.java:22756)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
 at android.view.View.updateDisplayListIfDirty(View.java:22712)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
 at android.view.View.updateDisplayListIfDirty(View.java:22712)
```

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. I'll check it.
