### ISSUE TITLE
StringIndexOutOfBoundsException when moving coursor to different part of text

### ISSUE THREAD

**Issue by sayler666** [MohamedRejeb/Compose-Rich-Editor#175]
To reproduce this just tap on different parts of text to move the cursor to them. 
It only happens if the text has new lines characters and when setting plain text with`RichTextState.setText()` method. 

This does not happen when using `RichTextState.setHtml()`. 

`java.lang.StringIndexOutOfBoundsException: length=0; index=1
                                                                                                    	at java.lang.String.substring(String.java:2479)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.slice(RichTextState.kt:1644)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.checkForParagraphs(RichTextState.kt:1083)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.updateTextFieldValue(RichTextState.kt:599)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.updateTextFieldValue$default(RichTextState.kt:594)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.onTextFieldValueChange$richeditor_compose_release(RichTextState.kt:586)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextEditorKt$BasicRichTextEditor$9$1.invoke(BasicRichTextEditor.kt:257)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextEditorKt$BasicRichTextEditor$9$1.invoke(BasicRichTextEditor.kt:249)
                                                                                                    	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:292)
                                                                                                    	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:290)
                                                                                                    	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:909)
                                                                                                    	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:904)
                                                                                                    	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand$foundation_release(TextFieldDelegate.kt:205)
                                                                                                    	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:254)
                                                                                                    	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:251)
                                                                                                    	at androidx.compose.ui.text.input.TextInputServiceAndroid$createInputConnection$1.onEditCommands(TextInputServiceAndroid.android.kt:135)
                                                                                                    	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEditInternal(RecordingInputConnection.android.kt:157)
                                                                                                    	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEdit(RecordingInputConnection.android.kt:151)
                                                                                                    	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$endBatchEdit$34(RemoteInputConnectionImpl.java:985)
                                                                                                    	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$8is00lwbkg8uMzkIkFQTXf-Y3P0(Unknown Source:0)
                                                                                                    	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda10.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

**Comment by MohamedRejeb** [comment]
Sorry for late reply, thanks for reporting this issue.
The fix will be available in the next release.
