### ISSUE TITLE
How to listen for value changes?

### ISSUE THREAD

**Issue by carbaj03** [MohamedRejeb/compose-rich-editor#382]
Is there something similar to the onValueChanged of the BasicTextField?

**Comment by MohamedRejeb** [comment]
For now there are no callbacks, you can use LaunchedEffect:

```kotlin
LaunchedEffect(richTextState.annotatedString) {
    println("Text changed: ${richTextState.annotatedString.text}")
}
```

**Comment by deepak-kynhood** [comment]
@MohamedRejeb 
How to listen for editor value update while copy-paste paragraph?
It's getting crash if a long text being pasted :

Please follow these steps (Android):  
Copy long text --> Open RTF editor --> Type some text manually--> Long tap and "Select All" and paste --> Getting crashed

java.lang.StringIndexOutOfBoundsException: begin 1598, end 1602, length 1600
                                                                                                    	at java.lang.String.checkBoundsBeginEnd(String.java:4500)
                                                                                                    	at java.lang.String.substring(String.java:2527)

**Comment by bpappin** [comment]
This is pretty crucial for compose since its a declarative ui. 
When can we expect this?

**Comment by MohamedRejeb** [comment]
Even compose now no longer has the `onValueChange` and using a similar approach, you can still listen to text or selection changes using the existing states:

```kotlin
LaunchedEffect(richTextState.annotatedString) {
    println("Text changed: ${richTextState.annotatedString.text}")
}

LaunchedEffect(richTextState.selection) {
    println("Selection changed: ${richTextState.selection}")
}
```
