### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Taltus1337** [MohamedRejeb/Compose-Rich-Editor#71]
`java.lang.StringIndexOutOfBoundsException: String index out of range: -2
                                                                                                    	at java.lang.String.substring(String.java:2064)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.removeUnorderedList(RichTextState.kt:403)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.toggleUnorderedList(RichTextState.kt:366)`

Error occours for example if you inserting a list:

- Point one
- Point two 

And than move the cursor to the very first position and than toggle list again.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, I'll check this

**Comment by MohamedRejeb** [comment]
Fixed in #72 I will publish a new release containing the fix within a few days
