### ISSUE TITLE
another java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Taltus1337** [MohamedRejeb/Compose-Rich-Editor#83]
`java.lang.StringIndexOutOfBoundsException: length=0; index=1
                                                                                                    	at java.lang.String.substring(String.java:2060)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.handleAddingCharacters(RichTextState.kt:670)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.onTextFieldValueChange$richeditor_compose_release(RichTextState.kt:510)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextEditorKt$BasicRichTextEditor$12$1.invoke(BasicRichTextEditor.kt:338)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextEditorKt$BasicRichTextEditor$12$1.invoke(BasicRichTextEditor.kt:335)
                                                                                                    	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:292)
                                                                                                    	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:290)
                                                                                                    	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:849)
                                                                                                    	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:844)
                                                                                                    	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand$foundation_release(TextFieldDelegate.kt:205)
                                                                                                    	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:254)
                                                                                                    	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:251)
                                                                                                    	at androidx.compose.ui.text.input.TextInputServiceAndroid$createInputConnection$1.onEditCommands(TextInputServiceAndroid.android.kt:128)
                                                                                                    	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEditInternal(RecordingInputConnection.android.kt:157)
                                                                                                    	at androidx.compose.ui.text.input.RecordingInputConnection.addEditCommandWithBatch(RecordingInputConnection.android.kt:131)
                                                                                                    	at androidx.compose.ui.text.input.RecordingInputConnection.commitText(RecordingInputConnection.android.kt:177)
                                                                                                    	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:339)
                                                                                                    	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7386)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)`

Found another StringIndexOutOfBoundsException, which occours by adding two linebreaks (enter) in an empty text field.

BTW Thank you for this nice Libary. This makes the developmet for my project much easier.

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, I'll fix this ASAP
