### ISSUE TITLE
crash happen when try to and new line in  OrderedList(

### ISSUE THREAD

**Issue by mohamedhamdy-Cis** [MohamedRejeb/Compose-Rich-Editor#96]
Hello mohamed 

I face crash when trying to edit the current text order list by add a new line I face this crash.

java.lang.StringIndexOutOfBoundsException: begin 103, end 109, length 108
                                                                                                    	at java.lang.String.checkBoundsBeginEnd(String.java:4466)
                                                                                                    	at java.lang.String.substring(String.java:2517)
                                                                                                    	at com.mohamedrejeb.richeditor.utils.AnnotatedStringExtKt.append-RcvT-LA(AnnotatedStringExt.kt:83)
                                                                                                    	at com.mohamedrejeb.richeditor.utils.AnnotatedStringExtKt.append-RcvT-LA(AnnotatedStringExt.kt:24)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.updateAnnotatedString(RichTextState.kt:597)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.updateTextFieldValue(RichTextState.kt:549)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.updateTextFieldValue$default(RichTextState.kt:533)
                                                                                                    	at com.mohamedrejeb.richeditor.model.RichTextState.onTextFieldValueChange$richeditor_compose_release(RichTextState.kt:525)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextEditorKt$BasicRichTextEditor$12$1.invoke(BasicRichTextEditor.kt:338)
                                                                                                    	at com.mohamedrejeb.richeditor.ui.BasicRichTextEditorKt$BasicRichTextEditor$12$1.invoke(BasicRichTextEditor.kt:335)
                                                                                                    	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:292)
                                                                                                    	at androidx.compose.foundation.text.BasicTextFieldKt$BasicTextField$8$1.invoke(BasicTextField.kt:290)
                                                                                                    	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:849)
                                                                                                    	at androidx.compose.foundation.text.TextFieldState$onValueChange$1.invoke(CoreTextField.kt:844)

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for reporting this issue. I'll fix it ASAP.
Can you please confirm that you are using the latest version `1.0.0-beta02`

**Comment by mohamedhamdy-Cis** [comment]
Thanks Mohamed for your quick interaction,
yes I use the latest version 1.0.0-beta02

**Comment by MohamedRejeb** [comment]
I'm going to publish a new release with the fix in the next few days.
